spring.application.name=zentia-backend

#Configuracion de MySQL (Cambia usuario y contrseña)
spring.datasource.url= jdbc:mysql://localhost:3306/zentia_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root2003

# Hibernate Auto-creación
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret (Debe ser larga y segura)
zentia.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
zentia.google.client-id=922881704825-u2ltn8v0ljfir5s0ghm6g64at8qqfijo.apps.googleusercontent.com
